version: '3'
services:
  mongodb:
    container_name: users_mongodb
    image: mongo
    ports:
     - "27017:27017"
  web:
    build: .
    ports:
      - "3000:${PORT}"
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb