version: '3'
services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - ./database/data/db:/data/db
    ports:
     - "27017:27017"
  web:
    build: .
    ports:
      - "3000:${PORT}"
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb